/*
### Build
const metadata = getMetadata()!! HUSK!
const autoGenerated = generateCss(theme, options)
const customCss = getCustomComponents() // string (uses fs)
// Then we write customCss to customCss.js
const fullCss = metadata + autoGenerated + br + customCss
// Then we write fullCss back to css-components.css (to have newest version)

HUSK Å LØSE METADATA!! Fra package json
*/

// Kanskje bare lage metadata i en egen js-string også? Putte alt inn i en build mappe? Eller bare en build.js fil?

import { copyFileSync, existsSync, mkdirSync, readFileSync, write, writeFileSync } from 'fs'
import { generateAutoCss, Css } from '../lib/generate-auto-css.js'

// Generate metadata
console.log('- Reading metadata from package.json, and creating css-metadata...')
const metadata = JSON.parse(readFileSync('./package.json', 'utf-8'))

const metadataCss = new Css()
metadataCss.addLine(`/* ${metadata.name} - ${metadata.description} */`)
metadataCss.addLine(`/* VERSION: ${metadata.version} */`)
metadataCss.addLine(`/* License: ${metadata.license} */`)
metadataCss.addLine()

console.log(`✅ Css metadata successfully created - ${metadata.name} - ${metadata.version}`)

// Generate auto css
console.log('- Generating auto-css...')
const autoGeneratedCss = generateAutoCss()
console.log('✅ Auto-css successfully generated')

// Get custom css. Remove autogenerated css from components.css if present - we merge it back in with new autogenerated css to get latest changes
console.log('- Reading custom css and removing autogenerated css from custom css file if it exist...')
const customCssContent = readFileSync('./lib/components.css', 'utf-8')

let endOfAutoIndex = customCssContent.indexOf(autoGeneratedCss.endAutoCssLine)
if (endOfAutoIndex === -1) {
  console.log('! Could not find end of auto-content line, probably first build, or someone has removed it... (if someone removed it, please go back to the version where it was present)')
  endOfAutoIndex = 0
} else {
  endOfAutoIndex += autoGeneratedCss.endAutoCssLine.length + 2 // +2 to include newlines
}

const customCss = customCssContent.substring(endOfAutoIndex)
console.log('✅ Custom css successfully read')

// Create helper js files for web (to avoid using fs in browser)
if (!existsSync('./web')) {
  console.log('- Web dir does not exist, creating...')
  mkdirSync('./web')
  console.log('✅ Web dir successfully created')
}

// Create helper js files for web (to avoid using fs in browser)
if (!existsSync('./web/scripts')) {
  console.log('- web/scripts dir does not exist, creating...')
  mkdirSync('./web/scripts')
  console.log('✅ Web/scripts successfully created')
}

console.log('- Writing metadata.js in web/scripts dir...')
writeFileSync('./web/scripts/DONT_EDIT-metadata.js', `export const cssMetadata = \`${metadataCss.css}\``)
console.log('✅ metadata.js successfully created')

console.log('- Writing custom-css.js in web/scripts dir...')
writeFileSync('./web/scripts/DONT_EDIT-custom-css.js', `export const customCss = \`${customCss}\``)
console.log('✅ custom-css.js successfully created')

// Merge all css
const fullCss = metadataCss.css + autoGeneratedCss.css + customCss
console.log('- Overwriting components.css...')
writeFileSync('./lib/components.css', fullCss)
console.log('✅ components.css successfully updated')

// Add generate-auto-css.js to web/scripts
console.log('- Writing generate-auto-css.js in web/scripts dir...')
copyFileSync('./lib/generate-auto-css.js', './web/scripts/DONT_EDIT-generate-auto-css.js')
console.log('✅ auto-generate-css.js successfully created')

/*
console.log('- Writing full css to build dir...')
writeFileSync('./build/style.css', fullCss)
console.log('✅ style.css successfully updated')
*/

console.log('👍 Build complete!')

